resources:
  - kind: repository
    selector:
      query: '.name == "walmart-microservices-demo"'
    port:
      entity:
        mappings:
          identifier: .full_name
          title: .name
          blueprint: '"githubRepository"'
          properties:
            readme: file://README.md
            url: .html_url
            defaultBranch: .default_branch
  - kind: repository
    selector:
      query: '.name == "walmart-microservices-demo"'
    port:
      entity:
        mappings:
          identifier: .full_name
          title: .full_name
          blueprint: '"service"'
          relations:
            repository: .full_name
